version: "2"

volumes:
  service_modules:
  mongo-data:
    driver: local

services:
  example_app:
    container_name: example_api_app
    build: .
    command: sh -c 'npm run dev'
    ports: 
      - 3001:3000
    volumes:
    - .:/app
    - /node_modules
    links:
      - MongoDB
    environment:
      EXAMPLE_DATABASE: mongodb://MongoDB/dang-db
      PORT: 3000
  MongoDB:
    image: mongo:3.4.1
    volumes:
      - mongo-data:/data/db
